public with sharing class AlertDecorator {
    public static final String TYPE_PERSON = 'Person';
    public static final String TYPE_PROPERTY = 'Property';
    public static final String TYPE_TENANCY = 'Tenancy';

    public static final String CATEGORY_PROPERTY = 'Property';
    public static final String CATEGORY_ASBESTOS = 'Asbestos';
    public static final String CATEGORY_CUSTOMER = 'Customer';
    public static final String CATEGORY_DISABILITY = 'Disability';
    public static final String CATEGORY_AUTHORISATION_TYPE = 'Authorisation Type';

    public static final String SUB_CATEGORY_VULNERABLE = 'Vulnerable Customer';
    public static final String SUB_CATEGORY_RIGHT_TO_BUY = 'Right to Buy or Acquire';
    public static final String SUB_CATEGORY_SECTION_20 = 'Section 20 Consultation';
    public static final String SUB_CATEGORY_POWEROFATTORNEY = 'Has Power of Attorney';
    public static final String SUB_CATEGORY_DELEGATEDAUTHORITY = 'Has Delegated Authority';
    public static final String SUB_CATEGORY_GRANTED_POWEROFATTORNEY = 'Has Granted Power of Attorney';
    public static final String SUB_CATEGORY_GRANTED_DELEGATEDAUTHORITY = 'Has Granted Delegated Authority';
    public static final String SUB_CATEGORY_PERSON_UNDER_18 = 'Person is Under 18';
    public static final String SUB_CATEGORY_DEXTERITY_ISSUES = 'Dexterity issues';
    public static final String SUB_CATEGORY_MOBILITY_ISSUES = 'Mobility issues';
    
    public static final String BTF_ALERT_CREATE_UPDATE_VALIDATION_FLOW_NAME = 'BTF_Alert_Create_Update_Validations_based_on_profile';

}