public with sharing class ApplicationDecorator {
    public static string STARTER_TENANCY = 'Starter';
    public static string ASSURED_TENANCY = 'Assured';
    public static string SOLE_TENANCY = 'Sole';
    public static string JOINT_TENANCY = 'Joint';
    public static string YES = 'Yes';
    public static string NO = 'No';
    public static string APPLICANT_TYPE_TENANT = 'Tenant';
    public static string MAILING_ADDRESS_UPDATE_UPDATE_TO_PROPERTY_ADDRESS = 'Update to Property Address';
    public static string MAILING_ADDRESS_UPDATE_ADDRESS_NOT_PROPERTY_ADDRESS = 'Address will not be the property Address';
}