public with sharing class AuthorityAndDetailDecorator {
    public static final String CASETYPE_POA_NEW = 'Power of Attorney new';
    public static final String CASETYPE_POA_CHANGE = 'Power of Attorney change';
    public static final String CASETYPE_POA_REMOVE = 'Power of Attorney remove';
    public static final String CASETYPE_DA_NEW = 'Delegated Authority new';
    public static final String CASETYPE_DA_REMOVE = 'Delegated Authority Remove';
    public static final String REQUEST_POA_CASE = 'Power of Attorney Case';
    public static final String REQUEST_DA = 'Delegated Authority';
}