public with sharing class CaseRoleDecorator {
    public static final String CUSTOMER_ROLE = 'Customer';
    public static final String TENANT_ROLE = 'Tenant';
    public static final String REPORTER_ROLE = 'Reporter';
    public static final String FEEDBACK_PROVIDER_ROLE = 'Feedback Provider';
    public static final String PRIMARY_EMERGENCY_CONTACT_ROLE = 'Primary Emergency Contact';
    public static final String SECONDARY_EMERGENCY_CONTACT_ROLE = 'Secondary Emergency Contact';
    public static final String ACCUSED_PARTY_ROLE = 'Accused Party';
    public static final String WITNESS_ROLE = 'Witness';
    public static final String MP_ROLE = 'MP';
    public static final String SOLICITOR_ROLE = 'Solicitor';
    public static final String POLICE_ROLE = 'Police';
    public static final String OTHER_ROLE = 'Other';
    public static final String CUSTOMER_DECEASED_ROLE = 'Customer Deceased';
    public static final String PERSONATRISK_ROLE = 'Person at risk';
    public static final String POA_INQUIRER_ROLE = 'POA Inquirer';
    public static final String DA_INQUIRER_ROLE = 'DA Inquirer';
    public static final String POA_ROLE = 'POA';
    public static final String DA_ROLE = 'DA';
    public static final string OUTGOING_CUSTOMER_ROLE = 'Outgoing customer';
    public static final string APPLICANT_ROLE = 'Applicant';
    public static final String TENANT_REQUIRING_MOVE_ROLE = 'Tenant Requiring Move';
}