public with sharing class CaseMilestoneDecorator {
    
    public static final String CASE_MILESTONE_INITIAL_CONTACT = 'Initial Contact';
    public static final String CASE_MILESTONE_STAGE_ONE_ACKNOWLEDGEMENT = 'Stage One Acknowledgement Letter Sent';
    public static final String CASE_MILESTONE_STAGE_ONE_RESOLUTION = 'Stage One Response Letter Sent';
    public static final String CASE_MILESTONE_STAGE_TWO_ACKNOWLEDGEMENT = 'Stage Two Acknowledgement Letter Sent';
    public static final String CASE_MILESTONE_STAGE_TWO_RESOLUTION = 'Stage Two Response Letter Sent';
    public static final String CASE_MILESTONE_OMBUDSMAN = 'Ombudsman';
    public static final String CASE_MILESTONE_FIRST_CONTACT_ATTEMPT = 'First Contact Attempt';
    public static final String CASE_MILESTONE_FIRST_CONTACT = 'First Contact';
    public static final String CASE_MILESTONE_RESOLUTION = 'Resolution';
    public static final String CASE_MILESTONE_CUSTOMER_CONTACT = 'Customer Contact';
    public static final String CASE_MILESTONE_MUTUALEXCHANGEDECISION = 'Mutual Exchange Decision';
    public static final String CASE_MILESTONE_INITIALEMAIL = 'Initial Email';
    public static final String CASE_MILESTONE_EMAILRESPONSE = 'Email Response';


}