public with sharing class CustomPermissionDecorator {
    public static final String CP_CAN_CREATE_LETTINGS_CASE = 'CanCreateLettingsCaseCP';
    public static final String CP_CAN_CREATE_COMPLAINT_CASE_STAGE1 = 'CanCreateComplaintsCaseAtStage1CP';
    public static final String CP_CAN_CREATE_COMPLAINT_CASE_STAGE2 = 'CanCreateComplaintsCaseAtStage2CP';
    public static final String CP_CAN_CREATE_COMPLAINT_CASE_OMBUDSMAN = 'CanCreateComplaintsCaseAtOmbudsmanCP';
    public static final String CP_CAN_UPDATE_COMPLAINT_CASE_STAGE1 = 'CanUpdateComplaintsCaseAtStage1CP';
    public static final String CP_CAN_UPDATE_COMPLAINT_CASE_STAGE2 = 'CanUpdateComplaintsCaseAtStage2CP';
    public static final String CP_CAN_UPDATE_COMPLAINT_CASE_OMBUDSMAN = 'CanUpdateComplaintsCaseAtOmbudsmanCP';
    public static final String CP_CAN_UPDATE_LETTINGS_CASE = 'CanUpdateLettingsCaseCP';
    public static final String CP_ALLOW_TO_CHANGE_CLOSED_DMCCASE = 'AllowToChangeClosedDMCCaseCP';
}