public with sharing class CustomerTrustedDeviceDecorator {
    public static final String REVOKE_REASON_ALLDEVICECONSENTREVOKED = 'All devices consent revoked';
    public static final String PASSWORD_RESET_REVOKE_REASON = 'Password reset';
    public static final String ACCOUNT_LOCKED_LOGINDETAILS_REVOKE_REASON = 'Account locked - Login details';
    public static final String ACCOUNT_LOCKED_MFA_REVOKE_REASON = 'Account locked - MFA';
}