public class CustomerDetailsDecorator {
    public static final String GENDER_FEMALE = 'Female'; 
    public static final String GENDER_MALE = 'Male';
    public static final String MARITAL_STATUS_MARRIED = 'Married';
    public static final String MAIN_LANG_ENGLISH = 'English';
    public static final String TITLE_MR = 'MR';
    public static final String TITLE_DR = 'DR';
    public static final String PRONOUNS_HE_THEY = 'He/They';
    public static final String ETHINICITY_INDIAN = 'Asian/Asian British: Indian';
    public static final String RELIGION_MUSLIM = 'Muslim';
    public static final String DISABILITY_NO = 'No Disabilities';
    public static final String YH_DISABILITY = 'yhDisability';

}