public with sharing class EntitlementDecorator {
    
    public static final String COMPLAINT_ENTITLEMENT_PROCESS_NAME = 'Complaint Entitlement Process';
    public static final String MONEY_COACHNONG_ENTITLEMENT_PROCESS_NAME = 'Money Coaching Entitlement Process';
    public static final String TENANCY_COACHING_ENTITLEMENT_PROCESS_NAME = 'Tenancy Coaching Entitlement Process';
    public static final String COMPLAINT_SLA_STAGE_1_ACKNOWLEDGEMENT = 'Stage 1 Acknowledgement';
    public static final String COMPLAINT_SLA_STAGE_1_RESOLUTION = 'Stage 1 Resolution';
    public static final String COMPLAINT_SLA_STAGE_2_ACKNOWLEDGEMENT = 'Stage 2 Acknowledgement';
    public static final String COMPLAINT_SLA_STAGE_2_RESOLUTION = 'Stage 2 Resolution';
    public static final String CHANGES_ENTITLEMENT_PROCESS_NAME = 'Changes Entitlement Process';
    public static final String PERMISSION_ENTITLEMENT_PROCESS_NAME = 'Permission Entitlement Process';
    public static final String PLACE_ENTITLEMENT_PROCESS_NAME = 'Place Entitlement Process';
    public static final String TENANCY_ENTITLEMENT_PROCESS_NAME = 'Tenancy Entitlement Process';
    public static final String AWAABS_STD_ENTITLEMENT_PROCESS_NAME = 'Awaabs Law Standard Entitlement Process';
}