public with sharing class FlowDecorator {
    public static final String FLOW_ATF_CMSE_SYNC_START_DATE = 'ATF : Case MIlestone Event : Sync Start Date';
    public static final Blob PDF_BLOB = Blob.valueOf('Fake PDF Content');
    public static final String ALL_USERS = 'AllUsers';
    public static final String V = 'V';
    public static final String H2_ERROR = '<h2>Error</h2>';
    public static final String ROLE_STRING = 'Role';
    public static final String ROLE_AND_SUBORDINATES = 'RoleAndSubordinates';
    public static final String NO_Reply_Email = 'no_reply@yorkshirehousing.co.uk';
}