public with sharing class MutualExchangeDecorator {
    public static final String PROPERTY_TYPE_INTERNAL = 'Internal';
    public static final String PROPERTY_TYPE_EXTERNAL = 'External';
    public static final Integer DEED_OF_ASSIGNMENT_DIFFERENCE_DATE = -1;
    public static final String SUBSTRING_AFTER_TO = 'to ';
    public static final String TYPE_SOLE_TO_SOLE = 'Sole to Sole';
    public static final String TYPE_MUTUAL_EXCHANGE = 'Mutual exchange';
}