public with sharing class ServiceAppointmentDecorator {
    public static final String SOBJECT_APINAME = 'ServiceAppointment';
    public static final String STATUS_DISPATCHED = 'Dispatched';
    public static final String STATUS_SCHEDULED = 'Scheduled';
    public static final String STATUS_COMPLETED = 'Completed';
    public static final String STATUS_NONE = 'None';
    public static final String KEYWORD_FOR = 'for';
    public static final String HYPHEN = '-';
    public static final String SPACE = ' ';
    public static final String SHARE_ACCESS_EDIT = 'Edit';
    public static final String SHARE_ACCESS_MANUAL = 'Manual';
}