public with sharing class TenancyDecorator {
    public static final String TENANCY_TYPE_SOLO = 'Sole';
    public static final String TENANCY_TYPE_JOINT = 'Joint';
    public static final String TENANCY_AGREEMENT_TYPE_STARTER = 'Starter Tenancy';
    public static final String TENANCY_AGREEMENT_TYPE_ASSURED = 'Assured Tenancy';
    public static final String TENANCY_AGREEMENT_TYPE_RENT_TO_BUY = 'Rent to Buy';
    public static final String TENANCY_AGREEMENT_TYPE_ASSURED_SHORT_HOLD = 'Assured Shorthold Tenancy';
    public static final String REASON_END_DATE_CUSTOMER_DESEASED = 'Customer deceased';
    public static final String REASON_END_DATE_OTHER = 'Other';
    public static final String REASON_OTHER = 'Abandoned Property';
    public static final String PRIMARY_REASON_FOR_LEAVING_MUTUAL_EXCHANGE = 'Mutual Exchange';
    public static final String TENANCY_REASON_FOR_MUTUAL_EXCHANGE = 'Mutual Exchange';
    public static final String APPLICATION_METHOD_ASSIGNMENT = 'Assignment';
    public static final String YH_GAVE_NOTICE_TENANCY_END_DATE_REASON = 'YH Gave Notice';
    public static final String OTHER_TENANCY_END_DATE_REASON = 'Other';
    public static final String CUSTOMER_DECEASED_TENANCY_END_DATE_REASON = 'Customer deceased';
    public static final String MANAGED_MOVE_TENANCY_END_DATE_REASON = 'Managed move';
    public static final String TRANSFER_TENANCY_END_DATE_REASON = 'Transfer';
    public static final String NO_CONF_KEY_ARE_RETURNED_TENANCY_END_DATE_REASON = 'No Confirmation Keys Are Returned';
    public static final String EXTEND_NOTICE_PERIOD_TENANCY_END_DATE_REASON = 'Extend Notice Period';
    public static final String TENANCY_END_DATE_ON_SUNDAY = 'Sunday';
    public static final String CUSTOMER_SHARING_REASON_TENANCY = 'Tenancy';
    public static final String TENANCY_SHARING = 'TenancySharing';

    public static final String CHARGE_FREQUENCY_RYEDALE_WEEKLY = 'Ryedale Weekly';
    public static final String CHARGE_FREQUENCY_CRAVEN_WEEKLY = 'Craven Weekly';
    public static final String CHARGE_FREQUENCY_SUPPORT_WEEKS_WEEKLY = 'Support Weeks Weekly';
    public static final String CHARGE_FREQUENCY_RHA_HOMELESS = 'RHA Homeless';
    public static final String CHARGE_FREQUENCY_RYEDALE_SHARED_OWNERSHIP = 'Ryedale Shared Ownership';
    public static final String CHARGE_FREQUENCY_MARKET_RENTS = 'Market Rents';
    public static final String CHARGE_FREQUENCY_RYEDALE_MONTHLY_HOME_OWNERS = 'Ryedale Monthly Home Owners';
    public static final String CHARGE_FREQUENCY_CRAVEN_MONTHLY_CALENDAR = 'Craven Monthly Calendar';
    public static final String CHARGE_FREQUENCY_CRAVEN_QUARTERLY_RTBS = 'Craven Quarterly RTB\'s';
    public static final String CHARGE_FREQUENCY_QUARTERLY = 'Quarterly';
    public static final String CHARGE_FREQUENCY_QUARTERLY_DEBIT_WEEKLY_BALS = 'Quarterly Debit Weekly Bals';
}