@isTest
public with sharing class UthPermissionSet {

    public static final String PROFILE_NAME_MONEY_COACHING_CASE_CREATE = PermissionSetDecorator.PS_CAN_CREATE_MONEY_COACHING_CASE;
    public static final String PROFILE_NAME_MONEY_COACHING_CASE_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_MONEY_COACHING_CASE;
    public static final String PROFILE_NAME_LETTINGS_CASE_CREATE = PermissionSetDecorator.PS_CAN_CREATE_LETTINGS_CASE;
    public static final String PROFILE_NAME_LETTINGS_CASE_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_LETTINGS_CASE;
    public static final String PROFILE_NAME_COMPLAINT_CASE_UPDATE_STAGE1 = PermissionSetDecorator.PS_CAN_UPDATE_COMPLAINT_CASE_STAGE1;
    public static final String PROFILE_NAME_COMPLAINT_CASE_CREATE_STAGE1 = PermissionSetDecorator.PS_CAN_CREATE_COMPLAINT_CASE_STAGE1;
    public static final String PROFILE_NAME_COMPLAINT_CASE_UPDATE_STAGE2 = PermissionSetDecorator.PS_CAN_UPDATE_COMPLAINT_CASE_STAGE2;
    public static final String PROFILE_NAME_COMPLAINT_CASE_CREATE_STAGE2 = PermissionSetDecorator.PS_CAN_CREATE_COMPLAINT_CASE_STAGE2;
    public static final String PROFILE_NAME_COMPLAINT_CASE_UPDATE_OMBUDSMAN = PermissionSetDecorator.PS_CAN_UPDATE_COMPLAINT_CASE_OMBUDSMAN;
    public static final String PROFILE_NAME_COMPLAINT_CASE_CREATE_OMBUDSMAN = PermissionSetDecorator.PS_CAN_CREATE_COMPLAINT_CASE_OMBUDSMAN;
    public static final String PROFILE_NAME_TENANCY_COACHING_CASE_CREATE = PermissionSetDecorator.PS_CAN_CREATE_TENANCY_COACHING_CASE;
    public static final String PROFILE_NAME_TENANCY_COACHING_CASE_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_TENANCY_COACHING_CASE;
    public static final String PROFILE_NAME_OMBUDSMAN_FIRSTREQFORACTION_CASE_CREATE = PermissionSetDecorator.PS_CAN_CREATE_OMBUDSMAN_FIRSTREQACTION_CASE;
    public static final String PROFILE_NAME_OMBUDSMAN_FIRSTREQFORACTION_CASE_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_OMBUDSMAN_FIRSTREQACTION_CASE;
    public static final String PROFILE_NAME_CUSTOMER_FEEDBACK_CASE_CREATE = PermissionSetDecorator.PS_CAN_CREATE_CUSTOMER_FEEDBACK_CASE;
    public static final String PROFILE_NAME_CUSTOMER_FEEDBACK_CASE_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_CUSTOMER_FEEDBACK_CASE;
    public static final String PROFILE_NAME_CEC_RT_CREATE = PermissionSetDecorator.PS_CAN_CREATE_CEC_CASE;
    public static final String PROFILE_NAME_CEC_RT_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_CEC_CASE;
    public static final String PROFILE_NAME_CEC_RT_UPDATE_AT_NEW = PermissionSetDecorator.PS_CAN_UPDATE_CEC_CASE_AT_NEW;
    public static final String PROFILE_NAME_CEC_RT_CREATE_AT_NEW = PermissionSetDecorator.PS_CAN_CREATE_CEC_CASE_AT_NEW;
    public static final String PROFILE_PS_CAN_UPDATE_SAFEGUARDING_CASE = PermissionSetDecorator.PS_CAN_UPDATE_SAFEGUARDING_CASE;
    public static final String PROFILE_NAME_PLACE_CASE_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_PLACE_CASE;
    public static final String PROFILE_NAME_PLACE_CASE_CREATE_AT_NEW = PermissionSetDecorator.PS_CAN_CREATE_PLACE_CASE_AT_NEW;
    public static final String PROFILE_NAME_PLACE_CASE_UPDATE_AT_NEW = PermissionSetDecorator.PS_CAN_UPDATE_PLACE_CASE_AT_NEW;
    public static final String PROFILE_NAME_BREACH_CASE_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_BREACH_CASE;
    public static final String PROFILE_NAME_BREACH_CASE_CREATE_AT_NEW = PermissionSetDecorator.PS_CAN_CREATE_BREACH_CASE_AT_NEW;
    public static final String PROFILE_NAME_BREACH_CASE_UPDATE_AT_NEW = PermissionSetDecorator.PS_CAN_UPDATE_BREACH_CASE_AT_NEW;
    public static final String PROFILE_NAME_PERMISSION_CASE_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_PERMISSION_CASE;
    public static final String PROFILE_NAME_PERMISSION_CASE_CREATE_AT_NEW = PermissionSetDecorator.PS_CAN_CREATE_PERMISSION_CASE_AT_NEW;
    public static final String PROFILE_NAME_PERMISSION_CASE_UPDATE_AT_NEW = PermissionSetDecorator.PS_CAN_UPDATE_PERMISSION_CASE_AT_NEW;
    public static final String PROFILE_NAME_TENANCY_CASE_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_TENANCY_CASE;
    public static final String PROFILE_NAME_TENANCY_CASE_CREATE_AT_NEW = PermissionSetDecorator.PS_CAN_CREATE_TENANCY_CASE_AT_NEW;
    public static final String PROFILE_NAME_TENANCY_CASE_UPDATE_AT_NEW = PermissionSetDecorator.PS_CAN_UPDATE_TENANCY_CASE_AT_NEW;
    public static final String PROFILE_NAME_CHANGES_CASE_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_CHANGES_CASE;
    public static final String PROFILE_NAME_CHANGES_CASE_CREATE_AT_NEW = PermissionSetDecorator.PS_CAN_CREATE_CHANGES_CASE_AT_NEW;
    public static final String PROFILE_NAME_CHANGES_CASE_UPDATE_AT_NEW = PermissionSetDecorator.PS_CAN_UPDATE_CHANGES_CASE_AT_NEW;
    public static final String PROFILE_NAME_SCHEMES_CASE_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_SCHEME_CASE;
    public static final String PROFILE_NAME_SCHEMES_CASE_CREATE = PermissionSetDecorator.PS_CAN_CREATE_SCHEME_CASE;
    public static final String PROFILE_NAME_DELETE_CONTENT_DOCUMENT = PermissionSetDecorator.PS_CAN_DELETE_CONTENT_DOCUMENT;
    public static final String PROFILE_NAME_MANAGEDMOVE_RT_CREATE = PermissionSetDecorator.PS_CAN_CREATE_MANAGEDMOVE_CASE;
    public static final String PROFILE_NAME_MANAGEDMOVE_RT_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_MANAGEDMOVE_CASE;
    public static final String PROFILE_NAME_TERMINATION_CASE_CREATE = PermissionSetDecorator.PS_CAN_CREATE_TERMINATION_AT_NEW;
    public static final String PROFILE_NAME_TERMINATION_CASE_UPDATE = PermissionSetDecorator.PS_CAN_UPDATE_TERMINATION;
    public static final String PROFILE_NAME_DMC_CASE_UPDATE = PermissionSetDecorator.PS_ALLOW_TO_CHANGE_CLOSED_DMCCASE;
    public static final String Bypass_CP_Case_TF_BIU_SETAWAITINGINFORMATIONCHANGEDATETIME = PermissionSetDecorator.PS_BYPASS_CP_Case_TF_BIU_SETAWAITINGINFORMATIONCHANGEDATETIME;
    public static final String FSL_RESOURCE_LICENSE = PermissionSetDecorator.FSL_RESOURCE_LICENSE;
    public static final String FSL_RESOURCE_PERMISSIONS = PermissionSetDecorator.FSL_RESOURCE_PERMISSIONS;
     
    public static List<PermissionSet> getAll(){
        return [SELECT Id FROM PermissionSet];
    }

    public static PermissionSet getByName(String name){
        return [SELECT Id FROM PermissionSet WHERE Name = :name LIMIT 1];
    }

    public static PermissionSetGroup getPSGByName(String name){
        return [SELECT Id, Status FROM PermissionSetGroup WHERE DeveloperName = :name LIMIT 1];
    }

    public static void setPermissionSet(Id assigneedId, String permissionSetId){
        insert new PermissionSetAssignment(AssigneeId=assigneedId,
                                   PermissionSetId=permissionSetId);
    }

    public static PermissionSetAssignment getPermissionSetAssignment(Id assigneedId, String permissionSetId){
        PermissionSetAssignment permissionSetAssignment = null;
        List<PermissionSetAssignment> permissionSetAssignmentsList = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId =: assigneedId
            AND PermissionSetId =: permissionSetId LIMIT 1];
        
        if (!permissionSetAssignmentsList.isEmpty()) {
            permissionSetAssignment = permissionSetAssignmentsList[0];
        }
        return permissionSetAssignment;
    }

    public static List<PermissionSetAssignment> getPermissionSetGrpAssignment(Id assigneedId, String permissionSetGrpId){
        return [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId = : assigneedId AND PermissionSetGroupId = : permissionSetGrpId];
    }
}